$c = [System.IO.File]::ReadAllText('jsc\evaluator.go')
$c = $c.Replace('runtime.JSValueNumber(n)', 'runtime.NewJSValueNumber(n)')
$c = $c.Replace('runtime.JSValueNumber(float64', 'runtime.NewJSValueNumber(float64')
$c = $c.Replace('runtime.JSValueString(s)', 'runtime.NewJSValueString(s)')
$c = $c.Replace('runtime.JSValueString("', 'runtime.NewJSValueString("')
$c = $c.Replace('runtime.JSValueTrue', 'runtime.JSValueTrue')
$c = $c.Replace('runtime.JSValueFalse', 'runtime.JSValueFalse')
$c = $c.Replace('runtime.JSValueNull', 'runtime.JSValueNull')
$c = $c.Replace('runtime.JSValueUndefined', 'runtime.JSValueUndefined')
$c = $c.Replace('runtime.JSValueNaN', 'runtime.NewJSValueNumber(math.NaN())')
[System.IO.File]::WriteAllText('jsc\evaluator.go', $c)
Write-Host 'done'
